create table Person(
    id int GENERATED by default as identity PRIMARY KEY ,
    name varchar NOT NULL ,
    age int CHECK ( age>0 ),
    email varchar UNIQUE
);

DROP TABLE person;

insert into person values (1,'Tom',18,'tom@mail.ru');
insert into person values (2,'Bob',28,'bob@mail.ru');
insert into person values (3,'Bob1',38,'bob123@mail.ru');
insert into person values (4,'Bob2',45,'bob123123@mail.ru');


